import 'package:flutter/material.dart';

import './models/category.dart';
import './models/meal.dart';

const DUMMY_CATEGORIES = const [
  Category(
    id: 'c1',
    title: 'Italian',
    color: Colors.purple,
  ),
  Category(
    id: 'c2',
    title: 'Indian',
    color: Colors.red,
  ),
  Category(
    id: 'c3',
    title: 'Hamburgers',
    color: Colors.orange,
  ),
  Category(
    id: 'c4',
    title: 'Gujarati     (ગુજરાતી)',
    color: Colors.amber,
  ),
  Category(
    id: 'c5',
    title: 'Light & Lovely',
    color: Colors.blue,
  ),
  Category(
    id: 'c6',
    title: 'Exotic',
    color: Colors.green,
  ),
  Category(
    id: 'c7',
    title: 'Breakfast',
    color: Colors.lightBlue,
  ),
  Category(
    id: 'c8',
    title: 'Asian',
    color: Colors.lightGreen,
  ),
  Category(
    id: 'c9',
    title: 'French',
    color: Colors.pink,
  ),
  Category(
    id: 'c10',
    title: 'Summer',
    color: Colors.teal,
  ),
];

const DUMMY_MEALS = const [
  Meal(
    id: 'm1',
    categories: [
      'c1',
      'c2',
    ],
    title: 'Spaghetti with Tomato Sauce',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Spaghetti_Bolognese_mit_Parmesan_oder_Grana_Padano.jpg/800px-Spaghetti_Bolognese_mit_Parmesan_oder_Grana_Padano.jpg',
    duration: 20,
    ingredients: [
      '4 Tomatoes',
      '1 Tablespoon of Olive Oil',
      '1 Onion',
      '250g Spaghetti',
      'Spices',
      'Cheese (optional)'
    ],
    steps: [
      'Cut the tomatoes and the onion into small pieces.',
      'Boil some water - add salt to it once it boils.',
      'Put the spaghetti into the boiling water - they should be done in about 10 to 12 minutes.',
      'In the meantime, heaten up some olive oil and add the cut onion.',
      'After 2 minutes, add the tomato pieces, salt, pepper and your other spices.',
      'The sauce will be done once the spaghetti are.',
      'Feel free to add some cheese on top of the finished dish.'
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm2',
    categories: [
      'c2',
    ],
    title: 'Pani Puri',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2018/07/11/21/51/toast-3532016_1280.jpg',
    duration: 10,
    ingredients: [
      '1 Slice White Bread',
      '1 Slice Ham',
      '1 Slice Pineapple',
      '1-2 Slices of Cheese',
      'Butter'
    ],
    steps: [
      'Butter one side of the white bread',
      'Layer ham, the pineapple and cheese on the white bread',
      'Bake the toast for round about 10 minutes in the oven at 200°C'
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm3',
    categories: [
      'c2',
      'c3',
    ],
    title: 'Classic Hamburger',
    affordability: Affordability.Pricey,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2014/10/23/18/05/burger-500054_1280.jpg',
    duration: 45,
    ingredients: [
      '300g Cattle Hack',
      '1 Tomato',
      '1 Cucumber',
      '1 Onion',
      'Ketchup',
      '2 Burger Buns'
    ],
    steps: [
      'Form 2 patties',
      'Fry the patties for c. 4 minutes on each side',
      'Quickly fry the buns for c. 1 minute on each side',
      'Bruch buns with ketchup',
      'Serve burger with tomato, cucumber and onion'
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm3',
    categories: [
      'c2',
      'c3',
    ],
    title: 'Dabeli',
    affordability: Affordability.Pricey,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2014/10/23/18/05/burger-500054_1280.jpg',
    duration: 45,
    ingredients: [
      '300g Cattle Hack',
      '1 Tomato',
      '1 Cucumber',
      '1 Onion',
      'Ketchup',
      '2 Burger Buns'
    ],
    steps: [
      'Form 2 patties',
      'Fry the patties for c. 4 minutes on each side',
      'Quickly fry the buns for c. 1 minute on each side',
      'Bruch buns with ketchup',
      'Serve burger with tomato, cucumber and onion'
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm5',
    categories: [
      'c2',
      'c5',
      'c10',
    ],
    title: 'Salad with Smoked Salmon',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2016/10/25/13/29/smoked-salmon-salad-1768890_1280.jpg',
    duration: 15,
    ingredients: [
      'Arugula',
      'Lamb\'s Lettuce',
      'Parsley',
      'Fennel',
      '200g Smoked Salmon',
      'Mustard',
      'Balsamic Vinegar',
      'Olive Oil',
      'Salt and Pepper'
    ],
    steps: [
      'Wash and cut salad and herbs',
      'Dice the salmon',
      'Process mustard, vinegar and olive oil into a dessing',
      'Prepare the salad',
      'Add salmon cubes and dressing'
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm6',
    categories: [
      'c6',
      'c10',
    ],
    title: 'Delicious Orange Mousse',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        'https://cdn.pixabay.com/photo/2017/05/01/05/18/pastry-2274750_1280.jpg',
    duration: 240,
    ingredients: [
      '4 Sheets of Gelatine',
      '150ml Orange Juice',
      '80g Sugar',
      '300g Yoghurt',
      '200g Cream',
      'Orange Peel',
    ],
    steps: [
      'Dissolve gelatine in pot',
      'Add orange juice and sugar',
      'Take pot off the stove',
      'Add 2 tablespoons of yoghurt',
      'Stir gelatin under remaining yoghurt',
      'Cool everything down in the refrigerator',
      'Whip the cream and lift it under die orange mass',
      'Cool down again for at least 4 hours',
      'Serve with orange peel',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm7',
    categories: [
      'c7',
    ],
    title: 'Pancakes',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2018/07/10/21/23/pancake-3529653_1280.jpg',
    duration: 20,
    ingredients: [
      '1 1/2 Cups all-purpose Flour',
      '3 1/2 Teaspoons Baking Powder',
      '1 Teaspoon Salt',
      '1 Tablespoon White Sugar',
      '1 1/4 cups Milk',
      '1 Egg',
      '3 Tablespoons Butter, melted',
    ],
    steps: [
      'In a large bowl, sift together the flour, baking powder, salt and sugar.',
      'Make a well in the center and pour in the milk, egg and melted butter; mix until smooth.',
      'Heat a lightly oiled griddle or frying pan over medium high heat.',
      'Pour or scoop the batter onto the griddle, using approximately 1/4 cup for each pancake. Brown on both sides and serve hot.'
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm8',
    categories: [
      'c8',
    ],
    title: 'Creamy Indian Chicken Curry',
    affordability: Affordability.Pricey,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://cdn.pixabay.com/photo/2018/06/18/16/05/indian-food-3482749_1280.jpg',
    duration: 35,
    ingredients: [
      '4 Chicken Breasts',
      '1 Onion',
      '2 Cloves of Garlic',
      '1 Piece of Ginger',
      '4 Tablespoons Almonds',
      '1 Teaspoon Cayenne Pepper',
      '500ml Coconut Milk',
    ],
    steps: [
      'Slice and fry the chicken breast',
      'Process onion, garlic and ginger into paste and sauté everything',
      'Add spices and stir fry',
      'Add chicken breast + 250ml of water and cook everything for 10 minutes',
      'Add coconut milk',
      'Serve with rice'
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm9',
    categories: [
      'c9',
    ],
    title: 'Chocolate Souffle',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        'https://cdn.pixabay.com/photo/2014/08/07/21/07/souffle-412785_1280.jpg',
    duration: 45,
    ingredients: [
      '1 Teaspoon melted Butter',
      '2 Tablespoons white Sugar',
      '2 Ounces 70% dark Chocolate, broken into pieces',
      '1 Tablespoon Butter',
      '1 Tablespoon all-purpose Flour',
      '4 1/3 tablespoons cold Milk',
      '1 Pinch Salt',
      '1 Pinch Cayenne Pepper',
      '1 Large Egg Yolk',
      '2 Large Egg Whites',
      '1 Pinch Cream of Tartar',
      '1 Tablespoon white Sugar',
    ],
    steps: [
      'Preheat oven to 190°C. Line a rimmed baking sheet with parchment paper.',
      'Brush bottom and sides of 2 ramekins lightly with 1 teaspoon melted butter; cover bottom and sides right up to the rim.',
      'Add 1 tablespoon white sugar to ramekins. Rotate ramekins until sugar coats all surfaces.',
      'Place chocolate pieces in a metal mixing bowl.',
      'Place bowl over a pan of about 3 cups hot water over low heat.',
      'Melt 1 tablespoon butter in a skillet over medium heat. Sprinkle in flour. Whisk until flour is incorporated into butter and mixture thickens.',
      'Whisk in cold milk until mixture becomes smooth and thickens. Transfer mixture to bowl with melted chocolate.',
      'Add salt and cayenne pepper. Mix together thoroughly. Add egg yolk and mix to combine.',
      'Leave bowl above the hot (not simmering) water to keep chocolate warm while you whip the egg whites.',
      'Place 2 egg whites in a mixing bowl; add cream of tartar. Whisk until mixture begins to thicken and a drizzle from the whisk stays on the surface about 1 second before disappearing into the mix.',
      'Add 1/3 of sugar and whisk in. Whisk in a bit more sugar about 15 seconds.',
      'whisk in the rest of the sugar. Continue whisking until mixture is about as thick as shaving cream and holds soft peaks, 3 to 5 minutes.',
      'Transfer a little less than half of egg whites to chocolate.',
      'Mix until egg whites are thoroughly incorporated into the chocolate.',
      'Add the rest of the egg whites; gently fold into the chocolate with a spatula, lifting from the bottom and folding over.',
      'Stop mixing after the egg white disappears. Divide mixture between 2 prepared ramekins. Place ramekins on prepared baking sheet.',
      'Bake in preheated oven until scuffles are puffed and have risen above the top of the rims, 12 to 15 minutes.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm10',
    categories: [
      'c2',
      'c5',
      'c10',
    ],
    title: 'Asparagus Salad with Cherry Tomatoes',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2018/04/09/18/26/asparagus-3304997_1280.jpg',
    duration: 30,
    ingredients: [
      'White and Green Asparagus',
      '30g Pine Nuts',
      '300g Cherry Tomatoes',
      'Salad',
      'Salt, Pepper and Olive Oil'
    ],
    steps: [
      'Wash, peel and cut the asparagus',
      'Cook in salted water',
      'Salt and pepper the asparagus',
      'Roast the pine nuts',
      'Halve the tomatoes',
      'Mix with asparagus, salad and dressing',
      'Serve with Baguette'
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm11',
    categories: [
      'c4',
      'c7'
    ],
    title: 'Gathiya',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
    'https://cdn.pixabay.com/photo/2018/07/10/21/23/pancake-3529653_1280.jpg',
    duration: 30,
    ingredients: [
      '2 cups besan (chick-pea flour)',
      '1/4 tsp baking soda',
      '1/4 tsp ajwain (thymol)',
      '1/4 tsp haldi (turmeric)',
      '1 Tbsp oil',
      '1/2 tsp salt tsp or to taste',
      'Oil to deep-fry',
    ],
    steps: [
      'Mix the besan, soda, ajwain, haldi, 1 tbsp oil and salt together.',
      'Add water and knead into a soft dough.',
      'Take a portion of the dough and place it on a greased surface.',
      'With base of your palm, drag the dough in a straight line, holding the dough at the starting point with the other hand.',
      'This will form a strip.',
      'Fry these strips over medium heat till crisp.'
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm12',
    categories: [
      'c4'
    ],
    title: 'Undhiyu',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
    'https://cdn.pixabay.com/photo/2018/07/10/21/23/pancake-3529653_1280.jpg',
    duration: 30,
    ingredients: [
      '100 gms yam- peeled and diced',
      '100 gms potato-peeled and diced',
      '100 gms beans-diced',
      '100 gms raw banana-diced',
      '1/2 tsp asafoetida',
      '1/2 tsp whole cumin',
      'Oil to fry',
      'For the muthiya:',
      '2 cups chickpea flour',
      '1 tsp kastoori methi',
      '1 tsp red chilli',
      '1 tsp sathri or lemon flower',
      '1 tsp sugar',
      '2 tsp oil for binding',
      'Salt to taste',
      '1/4 tsp cumin',
      '1/2 tsp turmeric',
      'For the masala:',
      '1 Tbsp grated coconut',
      '3 tsp coriander powder',
      '1/2 tsp cumin',
      '1 Tbsp fresh coriander- chopped',
      '1/2 tsp turmeric powder',
      '1 tsp red chilli powder',
      '1/2 tsp oil',
      'Salt to taste',
    ],
    steps: [
      'Lightly fry all the vegetables and keep aside.',
      'To prepare muthiya, mix all the ingredients in a bowl.',
      'Make small balls from this mixture and fry.',
      'To prepare the masala, mix all the ingredients. Keep aside.',
      'Heat oil in a pan and add asafoetida and cumin.',
      'Now add the masala mixture and cook for few minutes.',
      'Finally add all the vegetables and muthiya balls',
      'Cook till done.'
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm13',
    categories: [
      'c4'
    ],
    title: 'Kadhi(Curry) Khichdi',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
    'https://cdn.pixabay.com/photo/2018/07/10/21/23/pancake-3529653_1280.jpg',
    duration: 35,
    ingredients: [
      'Khichdi: '
      '1 tablespoon ghee or oil',
      '1/2 tsp cumin seeds',
      '1/8 tsp hing/asafetida',
      '1/2 tsp turmeric',
      '15 curry leaves',
      '1/2 cup onion diced',
      '1 tsp ginger grated',
      '4 garlic cloves minced',
      '2 green chillies/1/2 jalapeño minced',
      '1 cup white rice love short grain rice like soon masoori',
      '1 cup mixed lentils green gram/mung daal, red lentils/masoor daal, bengal gram/chana daal and split green gram/chilka mung daal',
      '2 tsp salt',
      '5 cups of water',
      'cilantro for garnish',
      'for Kadhi(Curry):',
      '1 cup plain yogurt full fat or low fat',
      '3 cups water',
      '2 tablespoon besan chickpea flour',
      '1 tablespoon ghee or oil',
      '1/4 tsp mustard seeds',
      '1/8 tsp hing/asafetida optional',
      '1/4 teaspoon fenugreek seeds optional',
      '2-4 cloves',
      '1 inch cinnamon stick',
      '1 tsp garlic minced',
      '2 green chillies 1/2 jalapeño, minced',
      '15 curry leaves',
      '1 tsp salt',
      '1-2 tsp sugar',
      'cilantro for garnish',
    ],
    steps: [
      'Rinse and drain rice and lentils.',
      'Turn Instant Pot to saute(more) mode. Once the hot sign displays add ghee or oil.',
      'Add cumin seeds and asafetida.',
      'Add onions, curry leaves, ginger, garlic and chillies',
      'Sauté for a minute.',
      'Add rinsed rice, lentils and salt. Mix well. ',
      'Add water, give a quick stir and close Instant Pot lid with pressure valve to sealing. Set Instant Pot to Manual(Hi) 6 mins.',
      'Open after 10 min, Garnish with cilantro.',
      'for kadhi(curry):',
      'In a mixing bowl, whisk together yogurt, water and besan. Keep aside.',
      'Set Instant Pot to saute(more) mode. Once the hot sign displays add ghee or oil.',
      'Add mustard seeds and allow them to splutter. Add hing, fenugreek seeds, cloves, cinnamon stick, garlic, green chilies and curry leaves. Saute for a minute.',
      'Carefully pour the whisked yogurt mix into the Instant Pot. Add salt and sugar, mix well.',
      'Close Instant Pot with pressure valve to sealing. Set Instant Pot to soup mode for 5 mins. Open after 10 min',
      'Add more water depending on the consistency you prefer and bring the kadhi to a full boil on sauté mode.',
      'Be very carefully if you need to open it before the 10 min - as the kadhi can spill out of the pressure valve.',
      'Do slow, short bursts of quick release if you need to open before the 10 minute, Garnish with cilantro.',
      'Enjoy hot with Khichdi or plain rice.',

    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm14',
    categories: [
      'c4',
    ],
    title: 'Khaman Dhokla',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
    'https://cdn.pixabay.com/photo/2018/07/10/21/23/pancake-3529653_1280.jpg',
    duration: 60,
    ingredients: [
      'Gram flour (besan) sieved 2 cups',
      'Yogurt beaten 1 cup',
      'Salt to taste',
      'Turmeric powder 1/2 teaspoon',
      'Green chilli-ginger paste 1 teaspoon',
      'Oil 2 tablespoons',
      'Lemon juice 1 tablespoon',
      'Soda bicarbonate 1 teaspoon',
      'Mustard seeds 1 teaspoon',
      'Fresh coriander leaves chopped 2 tablespoons',
      'Coconut scraped 1/2 cup',
    ],
    steps: [
      'Take gram flour in a bowl. Add yogurt and approximately one cup of warm water and mix. Avoid lumps. Add salt and mix again.',
      'Leave it aside to ferment for three to four hours. When gram flour mixture has fermented, add turmeric powder and green chilli-ginger paste. Mix. Heat the steamer. Grease a thali.',
      'In a small bowl take lemon juice, soda bicarbonate, one teaspoon of oil and mix. Add it to the batter and whisk briskly. Pour batter into the greased thali and place it in the steamer.',
      'Cover with the lid and steam for ten minutes. When a little cool, cut into squares and keep in a serving bowl/plate.',
      'Heat remaining oil in a small pan. Add mustard seeds. When the seeds begin to crackle, remove and pour over the dhoklas.',
      'Serve, garnished with chopped coriander leaves and scraped coconut.'
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm15',
    categories: [
      'c4',
      'c7'
    ],
    title: 'Thepla (Fenugreek Flatbread)',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
    'https://cdn.pixabay.com/photo/2018/07/10/21/23/pancake-3529653_1280.jpg',
    duration: 20,
    ingredients: [
      'Fresh fenugreek leaves (methi) chopped 1 cup',
      'Whole wheat flour (atta) 2 cups + for dusting',
      'Gram flour (besan) 1/4 cup',
      'Salt to taste',
      'Ginger-green chilli paste 1 a few drops',
      'Turmeric powder 1/4 teaspoon',
      'Red chilli powder 1/2 teaspoon',
      'White sesame seeds (til) 1 teaspoon',
      'Milk as required',
      'Oil 3-4 teaspoon',
    ],
    steps: [
      'Mix together wheat flour, gram flour, salt, ginger-green chilli paste, turmeric powder, chilli powder and fenugreek leaves in a bowl. Add sesame seeds and sufficient milk, mix and knead to a soft dough. Add oil and knead again.',
      'Divide the dough into equal portions, dust each portion with some wheat flour and roll out into thin discs or theplas.',
      'Heat a non-stick tawa. Place theplas on it, one by one, drizzle some oil and cook, turning sides, till evenly done on both sides.',
      'Serve hot with yogurt or mango pickle.',
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm16',
    categories: [
      'c4',
    ],
    title: 'Patra',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
    'https://cdn.pixabay.com/photo/2018/07/10/21/23/pancake-3529653_1280.jpg',
    duration: 40,
    ingredients: [
      '5 Colacasia leaves',
      'For Batter:',
      '150 Gram Gram flour',
      '100 Gram Tamarind pulp',
      '20 Gram Chilli powder',
      '5 Gram Turmeric powder',
      '2 Gram Asafoetida',
      '2 Gram Cumin seeds, roasted',
      '20 Gram Sugar',
      '20 Ml Oil',
      'To taste Salt',
      'For Tempering:',
      '30 Ml Oil',
      '5 Gram Mustard seeds',
      '10 Gram Sesame seeds',
      '25 Gram Coriander seeds',
      '75 Gram Coconut',
    ],
    steps: [
      'Chop the coriander leaves.',
      'Grate the coconut.',
      'Cut off the thick veins and wash the colacasia leaves.',
      'Mix the listed ingredients and make a thick batter',
      'Place a colacasia leaf on the table and spread a thin layer of the batter on top, place another leaf on top, repeat applying the batter. Fold in the sides of the leaf, then roll lengthwise into a tight roll.',
      'For cooking:',
      'Steam the rolls for 30 minutes.',
      'Remove and cut them into 1 cm thick slices.',
      'Arrange the slices on a platter.',
      'Heat the oil and add the mustard seeds, when they crackle add sesame, coriander leaves, and coconut.',
      'Pour this tempering on the sliced patra. Serve warm.',
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm17',
    categories: [
      'c4'
    ],
    title: 'Dal Dhokli',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
    'https://cdn.pixabay.com/photo/2018/07/10/21/23/pancake-3529653_1280.jpg',
    duration: 30,
    ingredients: [
      'For the dal:',
      '1 cup tuvar dal',
      '2 Tbsp peanuts-soaked in water for 30 minutes',
      '5 cloves garlic-chopped',
      '4 kokums',
      '1 tsp cumin seeds',
      '1/2 tsp turmeric powder',
      '1/2 tsp chilli powder',
      'For the dhokli:',
      '1 cup wheat flour (aata)',
      '1/2 tsp asafoetida',
      '1/2 tsp chilli powder',
      '1/2 tsp turmeric',
      'Oil',
      'Salt to taste',
    ],
    steps: [
      'Boil daal and the peanuts in a pressure cooker till soft. Keep aside.',
      'Heat 1 Tbsp ghee in a pan and add cumin seeds, garlic, asafoetida and finally, the boiled daal.',
      'Add cocum, turmeric powder, chilli powder, sugar and curry leaves. Boil and add salt to taste.',
      ' You can add vegetables also.',
      'To make the dhokli,',
      'mix the flour, salt, turmeric, chilli powder, asafoetida and a little oil and make a stiff dough with water. Knead well and roll out into 10 cm discs.',
      'Cut the discs into diamonds or squares with a knife and drop them into the boiling daal mixture.',
      'When all the dhokli pieces are put in, boil the daal for a further 15 minutes on a low fire. Garnish with coriander leaves and serve hot.',
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm18',
    categories: [
      'c4'
    ],
    title: 'SHRIKHAND - GUJARATI STYLE',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
    'https://cdn.pixabay.com/photo/2018/07/10/21/23/pancake-3529653_1280.jpg',
    duration: 50,
    ingredients: [
      '1 litre plain Greek yogurt',
      '¾ -1 cup powdered sugar',
      '5-6 -strands of saffron',
      '½ -1 tsp cardamom powder',
      '¼ tsp nutmeg powder',
      '10-12 almonds sliced or roughly chopped',
      '10-12 pistachios sliced or roughly chopped',
      '1 tsp milk',
    ],
    steps: [
      'Put the yogurt on a clean muslin or cotton cloth which you have draped over a sieve or a colander. Cover the yogurt with the cloth.',
      'Place a wad of newspaper on the cloth. Place some heavy object on it, like a clean stone, brick, mortar and pestle, etc whatever you have in the house.',
      'Leave it for about 15 minutes. All the water from the yogurt will drain out to give you a nice thick curd cheese.',
      'Heat about a teaspoon of milk and soak the saffron in it.',
      'Remove the curd cheese from the cloth and put it into a bowl. Add sugar to the curd cheese or strained yogurt. Mix well with a hand blender till the mixture is smooth.',
      'Add the cardamom, nutmeg and saffron milk. Mix well.',
      'The mixture will catch the saffron colour after a while. Can either sprinkle the nuts on top or mix it into the shrikhand. Whichever you prefer',
      'Chill for at least 30 minutes before serving.',
      'Tastes best when it is cold, just out of the fridge',
      'To serve as a dessert, can mix in fresh fruits like mangoes, grapes, pomegranate, tangerine, strawberries. Basically any fruit of our choice',

    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),



];
